name: 'Issue change labeler'
description: 'Label an issue if it has been modified in some way.'
inputs:
  changed-label:
    description: 'Label to track that an issue has been changed'
    required: true
    default: 'changed'
  qualifying-labels:
    description: 'Label(s) that must be on the issue already in order for changed labeling to trigger'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: gray-dark
  